from pygame.window import Window
from pygame.typing import ColorLike

GPU_SHADERSTAGE_VERTEX: int
GPU_SHADERSTAGE_FRAGMENT: int

def init() -> None: ...
def claim_window(window: Window) -> None: ...
def fill(window: Window, color: ColorLike) -> None: ...
def quit() -> None: ...

class Shader:
    def __init__(self, file: str, stage: int, samplers: int = 0, uniform_buffers: int = 0, storage_buffers: int = 0, storage_textures: int = 0): ...
