from pygame.window import Window
from pygame.typing import ColorLike

def init() -> None: ...
def claim_window(window: Window) -> None: ...
def fill(window: Window, color: ColorLike) -> None: ...
def quit() -> None: ...
