from pygame.window import Window
from pygame.typing import ColorLike, RectLike

GPU_SHADERSTAGE_VERTEX: int
GPU_SHADERSTAGE_FRAGMENT: int
GPU_LOADOP_LOAD: int
GPU_LOADOP_CLEAR: int
GPU_LOADOP_DONT_CARE: int
GPU_STOREOP_STORE: int
GPU_STOREOP_DONT_CARE: int
GPU_STOREOP_RESOLVE: int
GPU_STOREOP_RESOLVE_AND_STORE: int
GPU_PRIMITIVETYPE_TRIANGLELIST: int
GPU_PRIMITIVETYPE_TRIANGLESTRIP: int
GPU_PRIMITIVETYPE_LINELIST: int
GPU_PRIMITIVETYPE_LINESTRIP: int
GPU_PRIMITIVETYPE_POINTLIST: int
GPU_FILLMODE_FILL: int
GPU_FILLMODE_LINE: int

def init() -> None: ...
def claim_window(window: Window) -> None: ...
def submit() -> None: ...
def quit() -> None: ...


class Shader:
    def __init__(self, file: str, stage: int, samplers: int = 0, uniform_buffers: int = 0, storage_buffers: int = 0, storage_textures: int = 0): ...


class RenderPass:
    def __init__(self, clear_color: ColorLike, load_op: int, store_op: int): ...
    def begin(self, window: Window) -> None: ...
    def end(self) -> None: ...
    def draw_primitives(self, vertices: int, instances: int) -> None: ...
    def set_viewport(self, x: float, y: float, w: float, h: float, min_depth: float, max_depth: float) -> None: ...
    def set_scissor(self, rect: RectLike) -> None: ...


class Pipeline:
    def __init__(self, window: Window, vertex_shader: Shader, fragment_shader: Shader, primitive_type: int, fill_mode: int): ...
    def bind(self, render_pass: RenderPass) -> None: ...
